server:
  port: 8080
spring:
  application:
    name: demo-user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/producer
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
simply:
  eventable:
    entity-base-package: io.crcell.demo.entities
    topic-property:
      number-of-replicas: 1
      number-of-partitions: 10